# Generated by Django 5.0.1 on 2024-01-30 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_vehicletype_alter_vehicle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'verbose_name': 'Тип транспортного средства', 'verbose_name_plural': 'Типы транспортных средст'},
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('load_capacity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('number_of_seats', models.IntegerField()),
                ('fuel_capacity', models.IntegerField()),
                ('max_speed', models.IntegerField()),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto.vehicletype')),
            ],
        ),
    ]
