# Generated by Django 5.0.1 on 2024-01-30 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_alter_vehicletype_options_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Автомобильный бренд', 'verbose_name_plural': 'Автомобильные бренды'},
        ),
    ]
