# Generated by Django 5.0.1 on 2024-03-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0008_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Менеджер', 'verbose_name_plural': 'Менеджеры'},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='time_of_purchase',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
